export const types = {
  INIT_LOADING         : 'INIT_LOADING',
  SUBSCRIBE_ALL        : 'SUBSCRIBE_ALL',
  SUBSCRIBE_PROFILE    : 'SUBSCRIBE_PROFILE',
  SUBSCRIBE_SKILL      : 'SUBSCRIBE_SKILL',
  SUBSCRIBE_EXPERIENCE : 'SUBSCRIBE_EXPERIENCE'
} as const
